### ISSUE TITLE
Detecting natural ones 

### ISSUE THREAD

**Issue by Kittenlover229** [avrae/d20#3]
Does this library have a way to check for natural ones on rolls? I was walking the syntax tree, but it doesn't seep all that efficient.

**Comment by Infinidoge** [comment]
Yes, see [CritType.FAIL](https://d20.readthedocs.io/en/latest/api.html#d20.CritType.FAIL) and the method that can return it, [RollResult.crit](https://d20.readthedocs.io/en/latest/api.html#d20.RollResult.crit)
